name: Build PR 34

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Endundro's PR branch
      uses: actions/checkout@v4
      with:
        repository: Endundro/awesome_wotlk
        ref: epoch-ascension
        
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          
    - name: Build project
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        mingw32-make
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: awesome-wotlk-pr34-build
        path: |
          build/*.exe
          build/*.dll
        retention-days: 7
