name: Build PR 34 with Visual Studio (Fixed)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-2019  # Eski Windows sürümü kullan
    
    steps:
    - name: Checkout Endundro's PR branch
      uses: actions/checkout@v4
      with:
        repository: Endundro/awesome_wotlk
        ref: epoch-ascension
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup Visual Studio 2019
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2019
        
    - name: Create build directory
      run: mkdir build
      
    - name: Configure with CMake (x86)
      working-directory: build
      run: cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_GENERATOR_PLATFORM=Win32
      
    - name: Build project
      working-directory: build
      run: cmake --build . --config Release
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: awesome-wotlk-pr34-fixed-build
        path: |
          build/Release/*.exe
          build/Release/*.dll
          build/*.exe
          build/*.dll
        retention-days: 7
      if: always()
