name: Build PR 34 (Final Fix)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Endundro's PR branch
      uses: actions/checkout@v4
      with:
        repository: Endundro/awesome_wotlk
        ref: epoch-ascension
        submodules: recursive
        
    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Fix Detours compatibility
      run: |
        echo '#include <intrin.h>' > fix_intrinsics.h
        echo '#pragma intrinsic(_InterlockedExchangeAdd)' >> fix_intrinsics.h
        echo '#pragma intrinsic(_InterlockedCompareExchange)' >> fix_intrinsics.h
        echo '#pragma intrinsic(_InterlockedCompareExchange64)' >> fix_intrinsics.h
        copy fix_intrinsics.h deps\Detours\
        
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_CXX_FLAGS="/D_WIN32_WINNT=0x0601"
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: awesome-wotlk-pr34-final
        path: |
          build/Release/*.exe
          build/Release/*.dll
        retention-days: 7
      if: always()
